@{
    # Script module or binary module file associated with this manifest.
    # RootModule        = ''

    # Version number of this module.
    ModuleVersion     = '1.6.0'

    # ID used to uniquely identify this module
    GUID              = 'a272c231-f85d-416c-af92-9ae26c4d72dc'

    # Author of this module
    Author            = 'tomytate'

    # Company or vendor of this module
    CompanyName       = 'Open Source'

    # Copyright statement for this module
    Copyright         = '(c) 2026 tomytate. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Power User Windows Optimization Framework (PowerShell 7.6+ LTS)'

    # Minimum version of the PowerShell engine required by this module.
    PowerShellVersion = '7.6'

    # Supported PSEditions
    CompatiblePSEditions = @('Core')

    # HelpInfo URI of this module
    HelpInfoURI       = 'https://github.com/tomytate/Win-Debloat/blob/main/docs/'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules     = @(
        'src\core\Logger.psm1',
        'src\core\Config.psm1',
        'src\core\Registry.psm1',
        'src\core\State.psm1',
        'src\core\SystemState.psm1',
        'src\core\Sysprep.psm1',
        'src\modules\Bloatware\Bloatware.psm1',
        'src\modules\Privacy\Privacy.psm1',
        'src\modules\Performance\Performance.psm1',
        'src\modules\Repair\Repair.psm1',
        'src\modules\Features\Features.psm1',
        'src\modules\Security\Security.psm1',
        'src\modules\Performance\Gaming.psm1',
        'src\modules\Performance\Benchmark.psm1',
        'src\modules\Performance\Tweaks.psm1',
        'src\modules\Performance\Services.psm1',
        'src\modules\Maintenance\Maintenance.psm1',
        'src\modules\Windows11\Version-Detection.psm1',
        'src\modules\Software\Software.psm1',
        'src\modules\Drivers\Drivers.psm1',
        'src\modules\Network\Network.psm1',
        'src\modules\Privacy\Tasks.psm1',
        'src\modules\Privacy\Firewall.psm1',
        'src\modules\Integrations\Integrations.psm1',
        'src\modules\Vendor\Vendor.psm1',
        'src\modules\Tweaks\UI.psm1',
        'src\modules\Tweaks\System.psm1',
        'src\ui\Colors.psm1',
        'src\ui\Menu.psm1',
        'src\ui\gui\GUI.psm1'
    )

    # Functions to export from this module (100% AST Parity Synchronized)
    FunctionsToExport = @(
        'Add-WinDebloatFirewallBlock'
        'Clear-WinDebloatVersionCache'
        'Compare-WinDebloatBenchmarks'
        'Compare-WinDebloatSnapshot'
        'ConvertTo-WDRegistryType'
        'Disable-WinDebloatAI'
        'Disable-WinDebloatAIFabric'
        'Disable-WinDebloatAIRecall'
        'Disable-WinDebloatAutoBitLocker'
        'Disable-WinDebloatBitLockerHardening'
        'Disable-WinDebloatChatTaskbar'
        'Disable-WinDebloatClickToDo'
        'Disable-WinDebloatCopilot'
        'Disable-WinDebloatDeliveryOptimization'
        'Disable-WinDebloatDesktopSpotlight'
        'Disable-WinDebloatDirectSR'
        'Disable-WinDebloatDMAProtection'
        'Disable-WinDebloatEdgeAI'
        'Disable-WinDebloatFastStartup'
        'Disable-WinDebloatFindMyDevice'
        'Disable-WinDebloatGpuTelemetry'
        'Disable-WinDebloatIPv6'
        'Disable-WinDebloatLSAProtection'
        'Disable-WinDebloatModernStandbyNetworking'
        'Disable-WinDebloatNetAdapterRSC'
        'Disable-WinDebloatNetBIOS'
        'Disable-WinDebloatNotepadAI'
        'Disable-WinDebloatPaintAI'
        'Disable-WinDebloatPhoneLinkStart'
        'Disable-WinDebloatPUAProtection'
        'Disable-WinDebloatRecall'
        'Disable-WinDebloatRPCHardening'
        'Disable-WinDebloatScriptBlockLogging'
        'Disable-WinDebloatSettings365Ads'
        'Disable-WinDebloatSettingsHome'
        'Disable-WinDebloatShareDragTray'
        'Disable-WinDebloatSMBSigning'
        'Disable-WinDebloatSMBv1'
        'Disable-WinDebloatSnapAssist'
        'Disable-WinDebloatStartAllApps'
        'Disable-WinDebloatStickyKeysShortcut'
        'Disable-WinDebloatStorageSense'
        'Disable-WinDebloatTelemetryTasks'
        'Disable-WinDebloatTransparency'
        'Disable-WinDebloatUltimatePower'
        'Disable-WinDebloatWidgets'
        'Disable-WinDebloatWindowsSuggestions'
        'Disable-WinDebloatWPP'
        'Dismount-WinDebloatDefaultHive'
        'Enable-WinDebloatAIFabric'
        'Enable-WinDebloatAutoBitLocker'
        'Enable-WinDebloatBitLockerHardening'
        'Enable-WinDebloatChatTaskbar'
        'Enable-WinDebloatDeliveryOptimization'
        'Enable-WinDebloatDirectSR'
        'Enable-WinDebloatDMAProtection'
        'Enable-WinDebloatFastStartup'
        'Enable-WinDebloatFindMyDevice'
        'Enable-WinDebloatGpuTelemetry'
        'Enable-WinDebloatIPv6'
        'Enable-WinDebloatLSAProtection'
        'Enable-WinDebloatModernStandbyNetworking'
        'Enable-WinDebloatNetAdapterRSC'
        'Enable-WinDebloatNetBIOS'
        'Enable-WinDebloatPhoneLinkStart'
        'Enable-WinDebloatPrivacy'
        'Enable-WinDebloatPUAProtection'
        'Enable-WinDebloatRPCHardening'
        'Enable-WinDebloatScriptBlockLogging'
        'Enable-WinDebloatSettingsHome'
        'Enable-WinDebloatShareDragTray'
        'Enable-WinDebloatSMBSigning'
        'Enable-WinDebloatSMBv1'
        'Enable-WinDebloatSnapAssist'
        'Enable-WinDebloatStartAllApps'
        'Enable-WinDebloatStickyKeysShortcut'
        'Enable-WinDebloatStorageSense'
        'Enable-WinDebloatTelemetryTasks'
        'Enable-WinDebloatTransparency'
        'Enable-WinDebloatUltimatePower'
        'Enable-WinDebloatWidgets'
        'Enable-WinDebloatWindowsSuggestions'
        'Enable-WinDebloatWPP'
        'Export-RegistryKey'
        'Format-WD7Hyperlink'
        'Get-RegistryKey'
        'Get-WD7AnsiColor'
        'Get-WD7GradientText'
        'Get-WDRawRegistryKey'
        'Get-WDRegistryKeyState'
        'Get-WinDebloatBloatwareList'
        'Get-WinDebloatDNSProviders'
        'Get-WinDebloatDriverStatus'
        'Get-WinDebloatEssentialsList'
        'Get-WinDebloatFirewallStatus'
        'Get-WinDebloatGPUInfo'
        'Get-WinDebloatLanguageMode'
        'Get-WinDebloatLogPath'
        'Get-WinDebloatNetBIOSStatus'
        'Get-WinDebloatNetworkStatus'
        'Get-WinDebloatPrivacyScore'
        'Get-WinDebloatProfilePlan'
        'Get-WinDebloatProfileSummary'
        'Get-WinDebloatRecommendedProfile'
        'Get-WinDebloatRegistryTargets'
        'Get-WinDebloatSecurityStatus'
        'Get-WinDebloatServicePresets'
        'Get-WinDebloatServiceStatus'
        'Get-WinDebloatSnapshot'
        'Get-WinDebloatSnapshotDirectory'
        'Get-WinDebloatSnapshotSearchPaths'
        'Get-WinDebloatSystemState'
        'Get-WinDebloatTelemetryDomains'
        'Get-WinDebloatTelemetryTasks'
        'Get-WinDebloatVersionInfo'
        'Import-WinDebloatConfig'
        'Install-PackageManager'
        'Install-WinDebloatEssentials'
        'Install-WinDebloatProfileSoftware'
        'Install-WinDebloatSoftware'
        'Invoke-Profile'
        'Invoke-WD7PackageInstall'
        'Invoke-WinDebloatAdwCleaner'
        'Invoke-WinDebloatBenchmark'
        'Invoke-WinDebloatMaintenance'
        'Invoke-WinDebloatShutUp10'
        'Invoke-WinDebloatSysprepDefaults'
        'Measure-WinDebloatSystem'
        'Merge-WinDebloatConfigDictionaries'
        'Mount-WinDebloatDefaultHive'
        'New-WinDebloatSnapshot'
        'Optimize-WinDebloatComponentStore'
        'Optimize-WinDebloatDirectStorage'
        'Optimize-WinDebloatPerformance'
        'Optimize-WinDebloatThreadDirector'
        'Optimize-WinDebloatWinGetSettings'
        'Protect-WDData'
        'Protect-WinDebloatAMDX3D'
        'Protect-WinDebloatSudoPolicy'
        'Register-WinDebloatMaintenance'
        'Remove-LegacyWinDebloatHostsBlock'
        'Remove-RegistryKey'
        'Remove-WinDebloatBloatware'
        'Remove-WinDebloatCapabilities'
        'Remove-WinDebloatFirewallBlock'
        'Remove-WinDebloatOemBloat'
        'Repair-WinDebloatSystem'
        'Repair-WinDebloatUpdateError'
        'Reset-WinDebloatAMDX3D'
        'Reset-WinDebloatDirectStorage'
        'Reset-WinDebloatHAGSTDR'
        'Reset-WinDebloatNetwork'
        'Reset-WinDebloatShellCache'
        'Reset-WinDebloatThreadDirector'
        'Reset-WinDebloatUpdate'
        'Reset-WinDebloatWinGetSettings'
        'Resolve-WinDebloatProfileInheritance'
        'Restart-WinDebloatExplorer'
        'Restore-WDRegistryKey'
        'Restore-WinDebloatSnapshot'
        'Set-RegistryKey'
        'Set-WinDebloatContextMenu'
        'Set-WinDebloatContextMenuItems'
        'Set-WinDebloatDNS'
        'Set-WinDebloatExplorer'
        'Set-WinDebloatGaming'
        'Set-WinDebloatHAGSTDR'
        'Set-WinDebloatNetwork'
        'Set-WinDebloatOptionalFeatures'
        'Set-WinDebloatPrivacy'
        'Set-WinDebloatRegistryValue'
        'Set-WinDebloatSearch'
        'Set-WinDebloatSecurity'
        'Set-WinDebloatServices'
        'Set-WinDebloatStartMenu'
        'Set-WinDebloatSudoMode'
        'Set-WinDebloatSystemTweaks'
        'Set-WinDebloatTaskbarAlignment'
        'Set-WinDebloatTaskbarTweaks'
        'Set-WinDebloatTcpCongestionProvider'
        'Set-WinDebloatUpdateBehavior'
        'Show-AdvancedRemovalMenu'
        'Show-FeaturesMenu'
        'Show-IntegrationsMenu'
        'Show-MainMenu'
        'Show-NetworkPrivacyMenu'
        'Show-ProfilePreview'
        'Show-ProfileSelection'
        'Show-RepairMenu'
        'Show-SearchSuggestionsMenu'
        'Show-ServicesMenu'
        'Show-SnapshotMenu'
        'Show-SystemInfo'
        'Show-SystemQoLMenu'
        'Show-TweaksMenu'
        'Show-UICustomizationMenu'
        'Show-WD7ActionResult'
        'Show-WD7Breadcrumb'
        'Show-WD7Header'
        'Show-WD7Progress'
        'Show-WD7Separator'
        'Show-WD7StatusBadge'
        'Show-WinDebloatGUI'
        'Start-SnappyDriverInstaller'
        'Start-WinDebloatLogging'
        'Test-PackageManager'
        'Test-RegistryKey'
        'Test-WDRegistryValueEqual'
        'Test-WinDebloat11Version'
        'Test-WinDebloatConfig'
        'Test-WinDebloatPrinterIPPCompliance'
        'Test-WinDebloatProfile'
        'Test-WinDebloatSysprep'
        'Test-WinDebloatWhenGate'
        'Uninstall-WinDebloatEdge'
        'Uninstall-WinDebloatOneDrive'
        'Uninstall-WinDebloatXbox'
        'Unprotect-WDData'
        'Unregister-WinDebloatMaintenance'
        'Update-DriversViaWindowsUpdate'
        'Update-GPUDriverViaWinget'
        'Update-WinDebloatDrivers'
        'Update-WinDebloatSDIO'
        'Update-WinDebloatSoftware'
        'Wait-WD7UserPrompt'
        'Write-Log'
        'Write-WD7Host'
    )

    # Cmdlets to export from this module
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = @('ProfileSchema', 'SectionTypoMap', 'FieldTypoMap', 'typoMap')

    # Aliases to export from this module (100% Backward Compatibility Parity Synchronized)
    AliasesToExport = @(
        'Add-WinDebloat7FirewallBlock'
        'Clear-WinDebloat7VersionCache'
        'Clear-WindowsVersionCache'
        'Compare-WinDebloat7Benchmark'
        'Compare-WinDebloat7Benchmarks'
        'Compare-WinDebloat7Snapshot'
        'Compare-WinDebloatBenchmark'
        'ConvertTo-WD7RegistryType'
        'ConvertTo-WinDebloatRegistryType'
        'Disable-WD7ScriptBlockLogging'
        'Disable-WinDebloat7AI'
        'Disable-WinDebloat7AIandAds'
        'Disable-WinDebloat7AIFabric'
        'Disable-WinDebloat7AIRecall'
        'Disable-WinDebloat7AutoBitLocker'
        'Disable-WinDebloat7BitLockerHardening'
        'Disable-WinDebloat7ChatTaskbar'
        'Disable-WinDebloat7ClickToDo'
        'Disable-WinDebloat7Copilot'
        'Disable-WinDebloat7DeliveryOptimization'
        'Disable-WinDebloat7DesktopSpotlight'
        'Disable-WinDebloat7DirectSR'
        'Disable-WinDebloat7DMAProtection'
        'Disable-WinDebloat7EdgeAI'
        'Disable-WinDebloat7FastStartup'
        'Disable-WinDebloat7FindMyDevice'
        'Disable-WinDebloat7GpuTelemetry'
        'Disable-WinDebloat7IPv6'
        'Disable-WinDebloat7LSAProtection'
        'Disable-WinDebloat7ModernStandbyNetworking'
        'Disable-WinDebloat7NetAdapterRSC'
        'Disable-WinDebloat7NetBIOS'
        'Disable-WinDebloat7NotepadAI'
        'Disable-WinDebloat7PaintAI'
        'Disable-WinDebloat7PhoneLinkStart'
        'Disable-WinDebloat7Privacy'
        'Disable-WinDebloat7PUAProtection'
        'Disable-WinDebloat7Recall'
        'Disable-WinDebloat7RPCHardening'
        'Disable-WinDebloat7ScriptBlockLogging'
        'Disable-WinDebloat7Settings365Ads'
        'Disable-WinDebloat7SettingsHome'
        'Disable-WinDebloat7ShareDragTray'
        'Disable-WinDebloat7SMBSigning'
        'Disable-WinDebloat7SMBv1'
        'Disable-WinDebloat7SnapAssist'
        'Disable-WinDebloat7StartAllApps'
        'Disable-WinDebloat7StickyKeysShortcut'
        'Disable-WinDebloat7StorageSense'
        'Disable-WinDebloat7TelemetryTasks'
        'Disable-WinDebloat7Transparency'
        'Disable-WinDebloat7UltimatePower'
        'Disable-WinDebloat7Widgets'
        'Disable-WinDebloat7WindowsSuggestions'
        'Disable-WinDebloat7WPP'
        'Disable-WinDebloatAIandAds'
        'Disable-WinDebloatPrivacy'
        'Dismount-WinDebloat7DefaultHive'
        'Enable-WD7ScriptBlockLogging'
        'Enable-WinDebloat7AIFabric'
        'Enable-WinDebloat7AutoBitLocker'
        'Enable-WinDebloat7BitLockerHardening'
        'Enable-WinDebloat7ChatTaskbar'
        'Enable-WinDebloat7DeliveryOptimization'
        'Enable-WinDebloat7DirectSR'
        'Enable-WinDebloat7DMAProtection'
        'Enable-WinDebloat7FastStartup'
        'Enable-WinDebloat7FindMyDevice'
        'Enable-WinDebloat7GpuTelemetry'
        'Enable-WinDebloat7IPv6'
        'Enable-WinDebloat7LSAProtection'
        'Enable-WinDebloat7ModernStandbyNetworking'
        'Enable-WinDebloat7NetAdapterRSC'
        'Enable-WinDebloat7NetBIOS'
        'Enable-WinDebloat7PhoneLinkStart'
        'Enable-WinDebloat7Privacy'
        'Enable-WinDebloat7PUAProtection'
        'Enable-WinDebloat7RPCHardening'
        'Enable-WinDebloat7ScriptBlockLogging'
        'Enable-WinDebloat7SettingsHome'
        'Enable-WinDebloat7ShareDragTray'
        'Enable-WinDebloat7SMBSigning'
        'Enable-WinDebloat7SMBv1'
        'Enable-WinDebloat7SnapAssist'
        'Enable-WinDebloat7StartAllApps'
        'Enable-WinDebloat7StickyKeysShortcut'
        'Enable-WinDebloat7StorageSense'
        'Enable-WinDebloat7TelemetryTasks'
        'Enable-WinDebloat7Transparency'
        'Enable-WinDebloat7UltimatePower'
        'Enable-WinDebloat7Widgets'
        'Enable-WinDebloat7WindowsSuggestions'
        'Enable-WinDebloat7WPP'
        'Export-WinDebloat7RegistryKey'
        'Export-WinDebloatRegistryKey'
        'Format-WD7Link'
        'Format-WinDebloat7Hyperlink'
        'Format-WinDebloatHyperlink'
        'Get-WD7LanguageMode'
        'Get-WD7LogPath'
        'Get-WD7RawRegistryKey'
        'Get-WD7RegistryKeyState'
        'Get-WDLogPath'
        'Get-WinDebloat7GradientText'
        'Get-WinDebloatGradientText'
        'Get-WinDebloat7BloatwareList'
        'Get-WinDebloat7DNSProviders'
        'Get-WinDebloat7DriverStatus'
        'Get-WinDebloat7EssentialsList'
        'Get-WinDebloat7FirewallStatus'
        'Get-WinDebloat7GPUInfo'
        'Get-WinDebloat7LanguageMode'
        'Get-WinDebloat7LogPath'
        'Get-WinDebloat7NetBIOSStatus'
        'Get-WinDebloat7NetworkStatus'
        'Get-WinDebloat7PrivacyScore'
        'Get-WinDebloat7ProfilePlan'
        'Get-WinDebloat7ProfileSummary'
        'Get-WinDebloat7RecommendedProfile'
        'Get-WinDebloat7RegistryKey'
        'Get-WinDebloat7RegistryKeyState'
        'Get-WinDebloat7RegistryTargets'
        'Get-WinDebloat7SecurityStatus'
        'Get-WinDebloat7ServicePresets'
        'Get-WinDebloat7ServiceStatus'
        'Get-WinDebloat7Snapshot'
        'Get-WinDebloat7SnapshotDirectory'
        'Get-WinDebloat7SnapshotSearchPaths'
        'Get-WinDebloat7SystemState'
        'Get-WinDebloat7TelemetryDomains'
        'Get-WinDebloat7TelemetryTasks'
        'Get-WinDebloat7VersionInfo'
        'Get-WinDebloatRawRegistryKey'
        'Get-WinDebloatRegistryKey'
        'Get-WinDebloatRegistryKeyState'
        'Get-WindowsVersionInfo'
        'Import-WinDebloat7Config'
        'Install-WinDebloat7Essentials'
        'Install-WinDebloat7ProfileSoftware'
        'Install-WinDebloat7Software'
        'Invoke-WinDebloat7AdwCleaner'
        'Invoke-WinDebloat7Benchmark'
        'Invoke-WinDebloat7Maintenance'
        'Invoke-WinDebloat7SDIO'
        'Invoke-WinDebloat7ShutUp10'
        'Invoke-WinDebloat7SysprepDefaults'
        'Invoke-WinDebloatSDIO'
        'Measure-WinDebloat7System'
        'Merge-WinDebloat7ConfigDictionaries'
        'Mount-WinDebloat7DefaultHive'
        'New-WinDebloat7Snapshot'
        'Optimize-WinDebloat7ComponentStore'
        'Optimize-WinDebloat7DirectStorage'
        'Optimize-WinDebloat7Gaming'
        'Optimize-WinDebloat7Performance'
        'Optimize-WinDebloat7Services'
        'Optimize-WinDebloat7ThreadDirector'
        'Optimize-WinDebloat7WinGetSettings'
        'Optimize-WinDebloatGaming'
        'Optimize-WinDebloatServices'
        'Protect-WD7Data'
        'Protect-WinDebloat7AMDX3D'
        'Protect-WinDebloat7Data'
        'Protect-WinDebloat7SudoPolicy'
        'Protect-WinDebloatData'
        'Register-WinDebloat7Maintenance'
        'Remove-LegacyWinDebloat7HostsBlock'
        'Remove-WinDebloat7Bloatware'
        'Remove-WinDebloat7Capabilities'
        'Remove-WinDebloat7Capability'
        'Remove-WinDebloat7FirewallBlock'
        'Remove-WinDebloat7OemBloat'
        'Remove-WinDebloat7RegistryKey'
        'Remove-WinDebloatCapability'
        'Remove-WinDebloatRegistryKey'
        'Repair-WinDebloat7System'
        'Repair-WinDebloat7UpdateError'
        'Reset-WinDebloat7AMDX3D'
        'Reset-WinDebloat7DirectStorage'
        'Reset-WinDebloat7HAGSTDR'
        'Reset-WinDebloat7Network'
        'Reset-WinDebloat7ShellCache'
        'Reset-WinDebloat7ThreadDirector'
        'Reset-WinDebloat7Update'
        'Reset-WinDebloat7WindowsUpdate'
        'Reset-WinDebloat7WinGetSettings'
        'Reset-WinDebloatWindowsUpdate'
        'Resolve-WinDebloat7ProfileInheritance'
        'Restart-WinDebloat7Explorer'
        'Restore-WD7RegistryKey'
        'Restore-WinDebloat7RegistryKey'
        'Restore-WinDebloat7Snapshot'
        'Restore-WinDebloatRegistryKey'
        'Set-WinDebloat7ContextMenu'
        'Set-WinDebloat7ContextMenuItems'
        'Set-WinDebloat7DNS'
        'Set-WinDebloat7Explorer'
        'Set-WinDebloat7Features'
        'Set-WinDebloat7Gaming'
        'Set-WinDebloat7HAGSTDR'
        'Set-WinDebloat7Network'
        'Set-WinDebloat7OptionalFeatures'
        'Set-WinDebloat7Performance'
        'Set-WinDebloat7Privacy'
        'Set-WinDebloat7RegistryKey'
        'Set-WinDebloat7RegistryValue'
        'Set-WinDebloat7Search'
        'Set-WinDebloat7Security'
        'Set-WinDebloat7Services'
        'Set-WinDebloat7StartMenu'
        'Set-WinDebloat7SudoMode'
        'Set-WinDebloat7SystemTweaks'
        'Set-WinDebloat7TaskbarAlignment'
        'Set-WinDebloat7TaskbarTweaks'
        'Set-WinDebloat7TcpCongestionProvider'
        'Set-WinDebloat7TelemetryTasks'
        'Set-WinDebloat7UpdateBehavior'
        'Set-WinDebloatClassicContextMenu'
        'Set-WinDebloatFeatures'
        'Set-WinDebloatPerformance'
        'Set-WinDebloatRegistryKey'
        'Set-WinDebloatTelemetryTasks'
        'Show-WinDebloat7GUI'
        'Start-WD7Logging'
        'Start-WDLogging'
        'Start-WinDebloat7Logging'
        'Start-WinDebloat7Maintenance'
        'Start-WinDebloatMaintenance'
        'Test-WD7RegistryValueEqual'
        'Test-WinDebloat711Version'
        'Test-WinDebloat7Config'
        'Test-WinDebloat7PrinterIPPCompliance'
        'Test-WinDebloat7Profile'
        'Test-WinDebloat7RegistryKey'
        'Test-WinDebloat7RegistryValueEqual'
        'Test-WinDebloat7Sysprep'
        'Test-WinDebloat7Version'
        'Test-WinDebloat7WhenGate'
        'Test-WinDebloat7Windows11Version'
        'Test-WinDebloatRegistryKey'
        'Test-WinDebloatRegistryValueEqual'
        'Test-WinDebloatVersion'
        'Test-WinDebloatWindows11Version'
        'Test-Windows11Version'
        'Uninstall-WinDebloat7Edge'
        'Uninstall-WinDebloat7OneDrive'
        'Uninstall-WinDebloat7Xbox'
        'Unprotect-WD7Data'
        'Unprotect-WinDebloat7Data'
        'Unprotect-WinDebloatData'
        'Unregister-WinDebloat7Maintenance'
        'Update-WinDebloat7Driver'
        'Update-WinDebloat7Drivers'
        'Update-WinDebloat7SDIO'
        'Update-WinDebloat7Software'
        'Update-WinDebloatDriver'
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData       = @{
        PSData = @{
            Tags                     = @('Windows11', 'Optimization', 'Debloat', 'Performance', 'Gaming', 'Privacy', 'Security', 'PowerShell7')
            ProjectUri               = 'https://github.com/tomytate/Win-Debloat'
            LicenseUri               = 'https://github.com/tomytate/Win-Debloat/blob/main/LICENSE'
            IconUri                  = 'https://raw.githubusercontent.com/tomytate/Win-Debloat/main/assets/logo.png'
            HelpInfoURI              = 'https://github.com/tomytate/Win-Debloat/blob/main/docs/'
            RequireLicenseAcceptance = $false
            CompatiblePSEditions     = @('Core')
            ReleaseNotes             = 'Win-Debloat v1.6.0 with deep profile inheritance, 11-vector privacy score, Windows Protected Print, BitLocker XTS-256, DirectStorage 1.2, and AMD X3D core parking safeguards.'
        }
    }
}



